release:
  github:
    owner: knqyf263
    name: pet
  name_template: '{{.Tag}}'
brew:
  github:
    owner: knqyf263
    name: homebrew-pet
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  description: "Simple command-line snippet manager"
  homepage: "https://github.com/knqyf263/pet"
  dependencies:
    - fzf
  install: |
    bin.install Dir['pet']
    zsh_completion.install "misc/completions/zsh/_pet"
  test: |
    system "#{bin}/pet"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archive:
  format: zip
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - LICENSE*
  - README*
  - CHANGELOG*
  - misc/completions/zsh/_pet
fpm:
  bindir: /usr/local/bin
  formats:
  - deb
  - rpm
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
