release:
  github:
    owner: ramiawar
    name: superpet
  name_template: '{{.Tag}}'
brews:
  -
    tap:
      owner: ramiawar
      name: homebrew-superpet
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "Simple command-line snippet and environment manager"
    homepage: "https://github.com/ramiawar/superpet"
    dependencies:
      - fzf
    install: |
      bin.install Dir['pet']
      zsh_completion.install "misc/completions/zsh/_pet"
    test: |
      system "#{bin}/pet"
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  - "386"
  goarm:
  - "6"
  main: .
  ldflags: -s -w -X github.com/ramiawar/superpet/cmd.version={{.Version}}
archives:
  -
    format: tar.gz
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
      .Arm }}{{ end }}'
    files:
    - LICENSE*
    - README*
    - CHANGELOG*
    - misc/completions/zsh/_pet
