language: go

sudo: false
addons:
  apt:
    packages:
    - ruby
    - ruby-dev
    - build-essential
    - rpm

go:
  - "1.10.x"
  - "1.11.x"

script:
  - make dep
  - make test

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
